"""update_badge_model

Revision ID: 9295d27fdd18
Revises: 1d2f3a4b5c67
Create Date: 2026-02-24 22:26:10.579262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9295d27fdd18'
down_revision: Union[str, Sequence[str], None] = '1d2f3a4b5c67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    dialect_name = bind.dialect.name if bind is not None else ""

    if dialect_name == "sqlite":
        with op.batch_alter_table("badge") as batch_op:
            batch_op.add_column(sa.Column("slug", sa.String(), nullable=False, server_default=""))
            batch_op.add_column(sa.Column("category", sa.String(), nullable=True))
            batch_op.add_column(sa.Column("level", sa.String(), nullable=True))
            batch_op.add_column(sa.Column("rarity", sa.String(), nullable=True))
            batch_op.add_column(sa.Column("min_position", sa.Integer(), nullable=True))
            batch_op.add_column(sa.Column("is_active", sa.Boolean(), nullable=True))
        op.create_index(op.f("ix_badge_category"), "badge", ["category"], unique=False)
        op.create_index(op.f("ix_badge_slug"), "badge", ["slug"], unique=True)
        with op.batch_alter_table("userbadge") as batch_op:
            batch_op.create_unique_constraint(
                "uq_user_badge_season",
                ["user_id", "badge_id", "season_id"],
            )
    else:
        op.add_column("badge", sa.Column("slug", sa.String(), nullable=False))
        op.add_column("badge", sa.Column("category", sa.String(), nullable=True))
        op.add_column("badge", sa.Column("level", sa.String(), nullable=True))
        op.add_column("badge", sa.Column("rarity", sa.String(), nullable=True))
        op.add_column("badge", sa.Column("min_position", sa.Integer(), nullable=True))
        op.add_column("badge", sa.Column("is_active", sa.Boolean(), nullable=True))
        op.create_index(op.f("ix_badge_category"), "badge", ["category"], unique=False)
        op.create_index(op.f("ix_badge_slug"), "badge", ["slug"], unique=True)
        op.create_unique_constraint("uq_user_badge_season", "userbadge", ["user_id", "badge_id", "season_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    dialect_name = bind.dialect.name if bind is not None else ""

    if dialect_name == "sqlite":
        with op.batch_alter_table("userbadge") as batch_op:
            batch_op.drop_constraint("uq_user_badge_season", type_="unique")
        op.drop_index(op.f("ix_badge_slug"), table_name="badge")
        op.drop_index(op.f("ix_badge_category"), table_name="badge")
        with op.batch_alter_table("badge") as batch_op:
            batch_op.drop_column("is_active")
            batch_op.drop_column("min_position")
            batch_op.drop_column("rarity")
            batch_op.drop_column("level")
            batch_op.drop_column("category")
            batch_op.drop_column("slug")
    else:
        op.drop_constraint("uq_user_badge_season", "userbadge", type_="unique")
        op.drop_index(op.f("ix_badge_slug"), table_name="badge")
        op.drop_index(op.f("ix_badge_category"), table_name="badge")
        op.drop_column("badge", "is_active")
        op.drop_column("badge", "min_position")
        op.drop_column("badge", "rarity")
        op.drop_column("badge", "level")
        op.drop_column("badge", "category")
        op.drop_column("badge", "slug")
    # ### end Alembic commands ###
