"""Add badges and seasons

Revision ID: 94135f2cfc17
Revises: 5f03bf757949
Create Date: 2026-01-27 22:29:39.411929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94135f2cfc17'
down_revision: Union[str, Sequence[str], None] = '5f03bf757949'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_badge_id'), 'badge', ['id'], unique=False)
    op.create_index(op.f('ix_badge_name'), 'badge', ['name'], unique=True)
    op.create_table('season',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_season_id'), 'season', ['id'], unique=False)
    op.create_index(op.f('ix_season_name'), 'season', ['name'], unique=True)
    op.create_table('userbadge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('badge_id', sa.Integer(), nullable=True),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.Column('awarded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['badge_id'], ['badge.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_userbadge_badge_id'), 'userbadge', ['badge_id'], unique=False)
    op.create_index(op.f('ix_userbadge_id'), 'userbadge', ['id'], unique=False)
    op.create_index(op.f('ix_userbadge_season_id'), 'userbadge', ['season_id'], unique=False)
    op.create_index(op.f('ix_userbadge_user_id'), 'userbadge', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_userbadge_user_id'), table_name='userbadge')
    op.drop_index(op.f('ix_userbadge_season_id'), table_name='userbadge')
    op.drop_index(op.f('ix_userbadge_id'), table_name='userbadge')
    op.drop_index(op.f('ix_userbadge_badge_id'), table_name='userbadge')
    op.drop_table('userbadge')
    op.drop_index(op.f('ix_season_name'), table_name='season')
    op.drop_index(op.f('ix_season_id'), table_name='season')
    op.drop_table('season')
    op.drop_index(op.f('ix_badge_name'), table_name='badge')
    op.drop_index(op.f('ix_badge_id'), table_name='badge')
    op.drop_table('badge')
    # ### end Alembic commands ###
