from typing import Protocol


class VoteRepositoryPort(Protocol):
    async def exists_for_pair(self, *, voter_id: int, a_id: int, b_id: int) -> bool: ...
    async def add(self, vote: object) -> None: ...
    async def refresh(self, vote: object) -> None: ...


class ProfileRepositoryPort(Protocol):
    async def get_many_by_ids(self, ids: list[int]) -> list[object]: ...


class UnitOfWorkPort(Protocol):
    profiles: ProfileRepositoryPort
    votes: VoteRepositoryPort

    async def __aenter__(self) -> "UnitOfWorkPort": ...
    async def __aexit__(self, exc_type, exc, tb) -> None: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...
